config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/health_check', to: 'lb#health'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users

  root to: 'posts#top'
  resources :posts do
    resources :comments, only: %i[create destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_one_attached :image

  before_validation :set_no_title

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: false, length: { maximum: 15000 }

  belongs_to :user
  has_many :comments, dependent: :destroy

  private

  def set_no_title
    self.title = 'No Title' if title.blank?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_one_attached :image

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save
      flash[:notice] = 'コメントしました。'
      redirect_back(fallback_location: post_url(:post_id))
    else
      flash[:notice] = 'コメントできませんでした。'
      redirect_back(fallback_location: post_url(:post_id))
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    flash[:notice] = 'コメントを削除しました。'
    redirect_back(fallback_location: post_path(:post_id))
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/lb_controller.rb
class LbController < ApplicationController
  skip_before_action :login_required, only: [:health]
  def health
    render html: 'ok'
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]
  skip_before_action :login_required, only: [:top]
  def top
    render layout: false
  end

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(updated_at: :desc).page(params[:page]).per(15)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.all
    @comment = current_user.comments.build
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save!
      redirect_to posts_url, notice: '投稿が完了しました。'
    else
      reneder :new
    end
  end

  def edit; end

  def update
    @post.update!
    redirect_to posts_url, notice: '投稿を編集しました。'
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: '投稿を削除しました。'
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :image)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :login_required

  def new; end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to user_url(id: user.id), notice: 'ログインしました。'
    else
      flash[:notice] = 'メールアドレスかパスワードが間違っています。'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[new create]
  def index
    @users = User.order(updated_at: :desc).page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(id: @user.id), notice: 'ユーザーの新規登録が完了しました。'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    redirect_to users_url(@user), notice: 'ユーザーを更新しました。' if @user.update(user_params)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to posts_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/lb_helper.rb
module LbHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ShareInfo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body.bg-secondary
    .app-title.navbar.fixed-top.navbar-expand-md.navbar-dark.bg-dark role="navigation"
      = link_to "ShareInfo", { controller: :posts, action: :top }, class: 'navbar-brand'
      ul.nav.ml-auto
        -if current_user
          li = link_to '投稿一覧', posts_path, class: 'text-white mr-3'
          li = link_to '新規投稿', new_post_path, class: 'text-white mr-3'
          li = link_to 'マイユーザー', user_path(current_user.id), class: 'text-white mr-3'
          li = link_to 'ユーザー一覧', users_path, class: 'text-white mr-3'
          li = link_to 'ログアウト', logout_path, method: :delete, class: 'text-white mr-3'
        -else
          li = link_to 'アカウントを作る', new_user_path, class: 'text-white mr-3'
          li = link_to 'ログイン（テストユーザーでログインできます）', login_path, class: 'text-white mr-3'

    .container.mt-5.pt-3
      - if flash.notice.present?
        .alert.alert-info= flash.notice
      = yield

app/views/posts/_form.html.slim
- if post.errors.present?
ul#error_explanation
  - post.errors.full_messages.each do |message|
    li = message

= form_with model: post, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', id: 'post_title'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'post_description'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  = f.submit nil, class: 'btn btn-outline-light'

app/views/posts/edit.html.slim
h1 投稿の編集

= render partial: 'form', locals: { post: @post }

app/views/posts/index.html.slim
h1 投稿一覧

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row.mt-3
    = f.label :title_cont, 'タイトル', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :title_cont, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-light'
.mb-3
  = paginate @posts
  = page_entries_info @posts

.row
  - @posts.each do |post|
    .card.col-sm-4
      h5.card-header
        .media.bg-light
          - if post.user.image.attached?
            = image_tag post.user.image, class: 'icon-size mr-1 img-thumbnail'
          - else
            = image_tag 'icon.png', class: 'icon-size mr-1 img-thumbnail'
          .media-body
            h5.mt-2= link_to post.user.name, user_path(post.user.id), class:'text-dark'
      - if post.image.attached?
        = image_tag post.image, class:"card-img-top mt-2"
      - else
        = image_tag 'slide1.png', class:"card-img-top mt-2"
      .card-body.bg-light
        h4.card-title = post.title
        p.card-text = truncate(post.description, length: 35, omission: '...') do
          = link_to '続き', post
        = link_to '詳細', post, class: 'btn btn-outline-primary'
.mt-3.
  = paginate @posts
  = page_entries_info @posts

app/views/posts/new.html.slim
h1 新規投稿

= render partial: 'form', locals: { post: @post }

app/views/posts/show.html.slim
.row.mt-5
  .col-md-12
    .media.bg-light.px-2.py-3
      = image_tag @post.user.image, class: 'icon-size mr-3 img-thumbnail' if @post.user.image.attached?
      .media-body
        h5.mt-2= link_to @post.user.name, user_path(@post.user.id), class:'text-dark'
    .bg-light.px-5.pb-5.pt-2
      h1.pl-3= @post.title
      .text-right
        p= Post.human_attribute_name(:created_at)
        p= @post.created_at
      - if current_user == @post.user
        .float-right.mb-5
          = link_to '編集', edit_post_path, class:'btn btn-outline-primary mx-3'
          = link_to '削除', @post, method: :delete, data: { confirm: "投稿を削除します。よろしいですか？"}, class: 'btn btn-outline-danger mr-2' if current_user == @post.user
      p.pb-5 = simple_format(h(@post.description), {}, sanitize: false, wrapper_tag: "div")

    - @comments.each do |comment|
      .media.bg-light.px-2.py-3
        - if comment.user.image.attached?
          = image_tag comment.user.image, class: 'icon-size mr-3 img-thumbnail'
        - else
          = image_tag 'icon.png', class: 'icon-size mr-3 img-thumbnail'
        .media-body
          h5= link_to comment.user.name, user_path(comment.user.id), class:'text-dark'
          p= simple_format(h(comment.content), {}, sanitize: false, wrapper_tag: "div")
          = link_to '削除', post_comment_path(@post, comment), method: :delete, class: 'btn btn-outline-danger' if current_user == comment.user || current_user == @post.user

    .bg-light.px-5
      = form_with model: [@post, @comment], local: true do |f|
        = f.text_area :content, rows: 3, class: 'form-control'
        = f.submit 'コメントする', class: 'btn btn-dark mb-3 mt-2'

app/views/posts/top.html.slim
doctype html
html
  head
    title
      | ShareInfo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body.bg-secondary
    .app-title.navbar.fixed-top.navbar-expand-md.navbar-dark.bg-dark role="navigation"
      = link_to "ShareInfo", { controller: :posts, action: :top }, class: 'navbar-brand'
      ul.nav.ml-auto
        -if current_user
          li = link_to '投稿一覧', posts_path, class: 'text-white mr-3'
          li = link_to '新規投稿', new_post_path, class: 'text-white mr-3'
          li = link_to 'マイユーザー',"users/#{current_user.id}", class: 'text-white mr-3'
          li = link_to 'ユーザー一覧', users_path, class: 'text-white mr-3'
          li = link_to 'ログアウト', logout_path, method: :delete, class: 'text-white mr-3'
        -else
          li = link_to 'アカウントを作る', new_user_path, class: 'text-white mr-3'
          li = link_to 'ログイン（テストユーザーでログインできます）', login_path, class: 'text-white mr-3'
    #carousel.carousel.slide data-ride="carousel"
      ol.carousel-indicators
        li data-target="#carousel" data-slide-to="0" class="active"
        li data-target="#carousel" data-slide-to="1"
        li data-target="#carousel" data-slide-to="2"
      .carousel-inner
        .carousel-item.active
          = image_tag 'slide1.png', class:"d-block w-100"
          .carousel-caption.d-done.d-mg-block
            h1 ShareInfo
            h5.font-weight-light 情報を共有しよう。
        .carousel-item
          = image_tag 'slide2.png', class:"d-block w-100"
          .carousel-caption.d-done.d-mg-block
            h3.font-weight-light ShareInfoは誰でも簡単に投稿できる<br>情報共有サービスです。
        .carousel-item
          = image_tag 'slide3.png', class:"d-block w-100"
          .carousel-caption.d-done.d-mg-block
            h3.font-weight-light 今すぐ新規ユーザー登録しよう。
        a.carousel-control-prev href="#carousel" role="button" data-slide="prev"
          .carousel-control-prev-icon aria-hidden="true"
          .sr-only 前に戻る
        a.carousel-control-next href="#carousel" role="button" data-slide="next"
          .carousel-control-next-icon area-hidden="true"
          .sr-only 次に送る

app/views/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: user, local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-outline-light'

app/views/users/edit.html.slim
h1 ユーザーの編集

= render partial: 'form', locals: { user: @user }

app/views/users/index.html.slim
h1 ユーザー一覧
.mb-3
  = paginate @users
  = page_entries_info @users
.row.mt-3
  - @users.each do |user|
    .card.col-sm-4
      -if user.image.attached?
        = image_tag user.image, class: 'card-img-top mt-2'
      -else
        = image_tag 'slide2.png', class: 'card-img-top mt-2'
      .card-body.bg-light
        h3.card-text = user.name
        = link_to '詳細', user, class: 'btn btn-outline-primary justify-content-end'
.mt-3
  = paginate @users
  = page_entries_info @users

app/views/users/new.html.slim
h1 ユーザー登録

= render partial: 'form', locals: { user: @user }

app/views/users/show.html.slim
h1.mt-5.pt-2 ユーザーの詳細

table.table.table-hover
  tbody
    tr
      th プロフィール画像：
      td= image_tag @user.image, class: 'image-size' if @user.image.attached?
    tr
      th ユーザーネーム：
      td= @user.name
    tr
      th メールアドレス：
      td= @user.email
= link_to '編集', edit_user_path, class: 'btn btn-outline-primary mr-3'
= link_to '削除', @user, method: :delete, data: { confirm: "ユーザーを削除しますが、よろしいでしょうか？" }, class: 'btn btn-outline-danger'